name: Integration tests

on: [push, pull_request]

env:
  FILES_CHANGED: "all"
  MATRIX_SHARDS: 10

jobs:
  sanity-tests:
    name: Sanity tests
    runs-on: ubuntu-latest
    container:
      image: faucet/test-base:8.0.2
      options: --privileged --cap-add=ALL -v /lib/modules:/lib/modules -v /var/local/lib/docker:/var/lib/docker --sysctl net.ipv6.conf.all.disable_ipv6=0 --ulimit core=-1
    steps:
      - name: Apt stuff
        run: |
          apt-get update
          apt-get -y install kmod software-properties-common
          add-apt-repository -y ppa:git-core/ppa
          apt-get -y install git
      - name: Checkout repo
        uses: actions/checkout@v2
      - if: ${{ github.event_name == 'pull_request' }}
        name: Get file changes
        id: file_changes
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ steps.file_changes.outputs.all }}
        name: Compare file changes
        run: |
          FILES_ALL="$(echo '${{ steps.file_changes.outputs.all }}' | jq -r '.[]' | tr '\n' ' ')"
          FILES_ADDED="$(echo '${{ steps.file_changes.outputs.added }}' | jq -r '.[]' | tr '\n' ' ')"
          FILES_DELETED="$(echo '${{ steps.file_changes.outputs.deleted }}' | jq -r '.[]' | tr '\n' ' ')"
          FILES_RENAMED="$(echo '${{ steps.file_changes.outputs.renamed }}' | jq -r '.[]' | tr '\n' ' ')"
          FILES_MODIFIED="$(echo '${{ steps.file_changes.outputs.modified }}' | jq -r '.[]' | tr '\n' ' ')"
          FILES_ADDED_MODIFIED="${FILES_ADDED} ${FILES_MODIFIED}"
          PY_FILES_CHANGED="$(echo ${FILES_ADDED_MODIFIED} | tr ' ' '\n' | grep -E '\.py$' | tr '\n' ' ')"
          CI_TEST_FILES_CHANGED="$(echo ${FILES_ADDED_MODIFIED} | tr ' ' '\n' | grep -E '(workflows\/tests-.+\.yml$|Dockerfile\.tests$|^docker\/.+$|tests\/.+\.sh$)' | tr '\n' ' ')"
          RQ_FILES_CHANGED="$(echo ${FILES_ADDED_MODIFIED} | tr ' ' '\n' | grep -E 'requirements(.*)txt$' | tr '\n' ' ')"
          DOC_FILES_CHANGED="$(echo ${FILES_ADDED_MODIFIED} | tr ' ' '\n' | grep -E '^docs/.+$' | tr '\n' ' ')"
          echo "Files changed: ${FILES_ADDED_MODIFIED}"
          echo "CI test files changed: ${CI_TEST_FILES_CHANGED}"
          echo "Python code changed: ${PY_FILES_CHANGED}"
          echo "Requirement changes: ${RQ_FILES_CHANGED}"
          echo "Documentation changes: ${DOC_FILES_CHANGED}"
          if [ ! -z "${CI_TEST_FILES_CHANGED}" ]; then echo ::set-env name=FILES_CHANGED::all; else echo ::set-env name=FILES_CHANGED::${FILES_ADDED_MODIFIED}; fi
          echo ::set-env name=PY_FILES_CHANGED::${PY_FILES_CHANGED}
          echo ::set-env name=RQ_FILES_CHANGED::${RQ_FILES_CHANGED}
          echo ::set-env name=DOC_FILES_CHANGED::${DOC_FILES_CHANGED}
      - if: ${{ env.FILES_CHANGED == 'all' || env.PY_FILES_CHANGED || env.RQ_FILES_CHANGED }}
        name: Initialise environment
        run: |
          sysctl --quiet -w kernel.core_pattern="/var/tmp/core.%h.%e.%t"
          modprobe openvswitch
          modprobe ebtables
          ln -s "$(pwd)" /faucet-src
          cd /faucet-src/
      - if: ${{ env.FILES_CHANGED == 'all' || env.PY_FILES_CHANGED || env.RQ_FILES_CHANGED }}
        name: Run sanity tests
        run: |
          ./docker/runtests.sh
        env:
          FAUCET_TESTS: "-ni FaucetSanityTest FaucetStackStringOfDPUntaggedTest"
          HWTESTS: 1
      - name: Detect core dumps
        run: |
          if [ ls -1 /var/tmp/core* > /dev/null 2>&1 ]; then
            exit 1
          fi

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: sanity-tests
    container:
      image: faucet/test-base:8.0.2
      options: --privileged --cap-add=ALL -v /lib/modules:/lib/modules -v /var/local/lib/docker:/var/lib/docker --sysctl net.ipv6.conf.all.disable_ipv6=0 --ulimit core=-1
    strategy:
      matrix:
        MATRIX_SHARD: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - name: Apt stuff
        run: |
          apt-get update
          apt-get -y install kmod software-properties-common
          add-apt-repository -y ppa:git-core/ppa
          apt-get -y install git
      - name: Checkout repo
        uses: actions/checkout@v2
      - if: ${{ github.event_name == 'pull_request' && github.event.before != '0000000000000000000000000000000000000000' }}
        name: Get file changes
        id: file_changes
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ steps.file_changes.outputs.all }}
        name: Compare file changes
        run: |
          FILES_ALL="$(echo '${{ steps.file_changes.outputs.all }}' | jq -r '.[]' | tr '\n' ' ')"
          FILES_ADDED="$(echo '${{ steps.file_changes.outputs.added }}' | jq -r '.[]' | tr '\n' ' ')"
          FILES_DELETED="$(echo '${{ steps.file_changes.outputs.deleted }}' | jq -r '.[]' | tr '\n' ' ')"
          FILES_RENAMED="$(echo '${{ steps.file_changes.outputs.renamed }}' | jq -r '.[]' | tr '\n' ' ')"
          FILES_MODIFIED="$(echo '${{ steps.file_changes.outputs.modified }}' | jq -r '.[]' | tr '\n' ' ')"
          FILES_ADDED_MODIFIED="${FILES_ADDED} ${FILES_MODIFIED}"
          PY_FILES_CHANGED="$(echo ${FILES_ADDED_MODIFIED} | tr ' ' '\n' | grep -E '\.py$' | tr '\n' ' ')"
          CI_TEST_FILES_CHANGED="$(echo ${FILES_ADDED_MODIFIED} | tr ' ' '\n' | grep -E '(workflows\/tests-.+\.yml$|Dockerfile\.tests$|^docker\/.+$|tests\/.+\.sh$)' | tr '\n' ' ')"
          RQ_FILES_CHANGED="$(echo ${FILES_ADDED_MODIFIED} | tr ' ' '\n' | grep -E 'requirements(.*)txt$' | tr '\n' ' ')"
          DOC_FILES_CHANGED="$(echo ${FILES_ADDED_MODIFIED} | tr ' ' '\n' | grep -E '^docs/.+$' | tr '\n' ' ')"
          echo "Files changed: ${FILES_ADDED_MODIFIED}"
          echo "CI test files changed: ${CI_TEST_FILES_CHANGED}"
          echo "Python code changed: ${PY_FILES_CHANGED}"
          echo "Requirement changes: ${RQ_FILES_CHANGED}"
          echo "Documentation changes: ${DOC_FILES_CHANGED}"
          if [ ! -z "${CI_TEST_FILES_CHANGED}" ]; then echo ::set-env name=FILES_CHANGED::all; else echo ::set-env name=FILES_CHANGED::${FILES_ADDED_MODIFIED}; fi
          echo ::set-env name=PY_FILES_CHANGED::${PY_FILES_CHANGED}
          echo ::set-env name=RQ_FILES_CHANGED::${RQ_FILES_CHANGED}
          echo ::set-env name=DOC_FILES_CHANGED::${DOC_FILES_CHANGED}
      - if: ${{ env.FILES_CHANGED == 'all' || env.PY_FILES_CHANGED || env.RQ_FILES_CHANGED }}
        name: Initialise environment
        run: |
          sysctl --quiet -w kernel.core_pattern="/var/tmp/core.%h.%e.%t"
          modprobe openvswitch
          modprobe ebtables
          ln -s "$(pwd)" /faucet-src
          cd /faucet-src/
          shard_tests=$(./docker/shard_tests.sh "${{ env.MATRIX_SHARDS }}" "${{ matrix.MATRIX_SHARD }}")
          faucet_tests="-din ${shard_tests}"
          echo "Running the following faucet tests on this shard: ${shard_tests}"
          echo ::set-env name=FAUCET_TESTS::${faucet_tests}
      - if: ${{ env.FILES_CHANGED == 'all' || env.PY_FILES_CHANGED || env.RQ_FILES_CHANGED }}
        name: Run integration tests
        run: |
          ./docker/runtests.sh
      - name: Detect core dumps
        run: |
          if [ ls -1 /var/tmp/core* > /dev/null 2>&1 ]; then
            exit 1
          fi
